CREATE TABLE youtube
(
    youtube_id    BIGINT AUTO_INCREMENT NOT NULL,
    video_id      VARCHAR(255)          NULL,
    title         VARCHAR(255)          NULL,
    thumbnail_url VARCHAR(255)          NULL,
    publish_time  datetime              NULL,
    CONSTRAINT pk_youtube PRIMARY KEY (youtube_id)
);

INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (51,'Kc1zgNCdb1U','수영초보도 가능! 요즘 제주에서 가장 인기있는 해녀체험 도전해보기','https://i.ytimg.com/vi/Kc1zgNCdb1U/default.jpg','2022-06-29 18:00:09');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (52,'bmgao9b1zU4','제주도 2박3일 알찬 여행 🐳해녀 체험 후기 !🪼','https://i.ytimg.com/vi/bmgao9b1zU4/default.jpg','2024-08-11 18:30:31');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (53,'rrLsxrygnMA','해녀 할머님이 직접 잡아 제주 바다 한상 주시는 곳 #온평바다한그릇 #제주여행 #제주맛집','https://i.ytimg.com/vi/rrLsxrygnMA/default.jpg','2023-12-24 11:30:23');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (54,'0n7gbYcj9Rs','특별한 제주여행을 원한다면 해녀체험 추천🐙문어사냥 성공✨ #shorts #제주여행 #제주도여행 #해녀 #국내여행 #제주도물놀이 #도시해녀','https://i.ytimg.com/vi/0n7gbYcj9Rs/default.jpg','2023-06-07 20:00:01');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (55,'t1DN7Y-L9j4','[ENG] ※ 🦀고생 입水 완료 ※  장성규 드디어 잠수탐?ㄷㄷ 맑고 푸른 제주 바다에서 간만에 시원하게 고생 제대로 하고 왔다는 해녀체험 알바 리뷰 | 워크맨 ep.66','https://i.ytimg.com/vi/t1DN7Y-L9j4/default.jpg','2020-08-28 18:00:11');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (56,'JNuzFGc_s7Q','Jeju Vlog 🍊| 그랜드 하얏트 제주 | 호캉스 | 해녀체험 | 제주도 맛집 | 제주도 호텔 추천 | 흑돼지 맛집','https://i.ytimg.com/vi/JNuzFGc_s7Q/default.jpg','2024-11-29 00:53:32');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (57,'EUSc8nM1Fws','제주도 해녀체험으로 문어 잡았어요!🐙 ㅣ제주도 여행 VLOG ㅣ제주여행 추천 코스👍🏻ㅣJEJU','https://i.ytimg.com/vi/EUSc8nM1Fws/default.jpg','2020-06-26 18:00:06');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (58,'uvam9aI-tog','제주 2박 3일 물놀이 뽕 뽑기 #해녀체험 #판포포구','https://i.ytimg.com/vi/uvam9aI-tog/default.jpg','2023-08-15 09:46:48');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (59,'vdNAgaCj6z0','🇰🇷 혼술,혼밥 만렙 뚜벅이의 제주 혼자 여행 브이로그 2편','https://i.ytimg.com/vi/vdNAgaCj6z0/default.jpg','2024-11-28 17:15:02');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (60,'k5QkCVlMeQ4','배명호의 물 공포증 이겨내고 제주도 해녀 체험하기!','https://i.ytimg.com/vi/k5QkCVlMeQ4/default.jpg','2023-06-06 21:00:09');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (61,'kQPJVPQlaRk','노홍철이 갑자기 제주도 해녀가 된 이유는?','https://i.ytimg.com/vi/kQPJVPQlaRk/default.jpg','2024-09-12 18:15:03');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (62,'_lptKvT-FvA','제주도 해녀체험 하러가는 브이로그🤿🐙 크리에이터 20명과 함께하는 데이뉴 네트워킹✈️','https://i.ytimg.com/vi/_lptKvT-FvA/default.jpg','2024-07-19 14:07:45');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (63,'KmeC-iXxuV4','제주 해녀체험 수영 못하는 나도 할 수 있다! (w.도시해녀)','https://i.ytimg.com/vi/KmeC-iXxuV4/default.jpg','2022-07-21 08:16:00');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (64,'l9NxFUYODFo','우리들의 난리블루스ㅣ제주도해녀체험ㅣ제주해녀ㅣ제주도여행브이로그','https://i.ytimg.com/vi/l9NxFUYODFo/default.jpg','2022-06-13 17:48:20');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (65,'r5Gg4zUV78Q','최연소 해녀의 하루 수입은? #shorts','https://i.ytimg.com/vi/r5Gg4zUV78Q/default.jpg','2023-05-16 14:54:32');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (66,'aVPzco30tL0','제주도 하도어촌체험마을 해녀체험 | Jeju Island | Haenyeo | Experience | Korea | Travel','https://i.ytimg.com/vi/aVPzco30tL0/default.jpg','2022-08-27 00:49:22');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (67,'5uAe30bnb0k','사업망한 30대 여자 제주도에서 결국 해녀가 되기로 했습니다....','https://i.ytimg.com/vi/5uAe30bnb0k/default.jpg','2024-09-10 19:15:00');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (68,'APovoQSNHjc','제주 해녀가 바다를 두려워하는 슬픈 이유 #shorts / KBS','https://i.ytimg.com/vi/APovoQSNHjc/default.jpg','2024-03-05 17:30:02');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (69,'4Bt4jvl8vVU','제주 팜팜버스여행 하도리편! / 해녀체험 + 메이즈랜드 체험이 10,600원!','https://i.ytimg.com/vi/4Bt4jvl8vVU/default.jpg','2019-08-28 10:20:58');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (70,'1mtUy4jd-O8','제주도 해녀 체험기 + 하도 어촌 체험마을','https://i.ytimg.com/vi/1mtUy4jd-O8/default.jpg','2022-10-18 19:30:00');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (71,'RCe5Y7J1ft4','[리얼제주]외국인이 체험해 본 제주 해녀 문화','https://i.ytimg.com/vi/RCe5Y7J1ft4/default.jpg','2022-08-19 16:58:05');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (72,'eGCpGgQ3iPM','[다큐3일★풀버전] 제주 서귀포시 어촌계에 ‘해녀의 명맥’을 잇고자 하는 이들이 모여들었다 &quot;애기 해녀 숨비다 - 서귀포 해녀 인턴 72시간&quot; (KBS 20151025 방송)','https://i.ytimg.com/vi/eGCpGgQ3iPM/default.jpg','2021-10-08 20:00:11');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (73,'6KbPuQUwtAU','40초에 7소라를 캐내는 제주 상군 해녀 #shorts','https://i.ytimg.com/vi/6KbPuQUwtAU/default.jpg','2022-01-04 15:41:16');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (74,'ECjlXs7nez4','🌊바닷속 보물 캐는 MZ 세대 ‘최연소 해녀’ 등장! l 눈에 띄는 그녀들 3[1회] /YTN2','https://i.ytimg.com/vi/ECjlXs7nez4/default.jpg','2023-05-16 19:00:15');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (75,'SYir5tXjl4w','제주도 여행ㅣ해녀 체험 , 해루질 , 제주 바다를 배경으로 새벽 달리기','https://i.ytimg.com/vi/SYir5tXjl4w/default.jpg','2022-08-06 18:06:13');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (76,'Ej0ZmyQZ0Pc','대한민국 최초 외국인 해녀 탄생! 제주에 푹 빠져 해녀가 되기로 결심했다는 폴란드 여자│새내기 해녀 바다 나가 물질하는 날│고향민국│#골라듄다큐','https://i.ytimg.com/vi/Ej0ZmyQZ0Pc/default.jpg','2023-11-29 08:30:05');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (77,'eZOLvnQWyHI','[자막뉴스] 제주 놀러갔다 빌려탄 차…악몽의 시작이었다 / KBS 2023.06.09.','https://i.ytimg.com/vi/eZOLvnQWyHI/default.jpg','2023-06-09 16:40:00');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (78,'9HKDmXwAv-g','제주도 해녀체험💦#하도어촌마을#원데이클래스#해녀체험#제주원데이클래스#제주다이빙#프리다이빙','https://i.ytimg.com/vi/9HKDmXwAv-g/default.jpg','2023-06-27 01:19:49');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (79,'_ne2sqvlm0c','제주해녀체험 제주살이','https://i.ytimg.com/vi/_ne2sqvlm0c/default.jpg','2023-09-25 20:13:44');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (80,'pcCHYTmOooE','바다를 탐하다! 제주 해녀 체험 @생방송 투데이 2398회 20190823','https://i.ytimg.com/vi/pcCHYTmOooE/default.jpg','2019-08-23 20:29:10');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (81,'elzzYPkqdCo','어서와 해녀는 처음이지? 🐙🐚제주도 해녀체험 vlog','https://i.ytimg.com/vi/elzzYPkqdCo/default.jpg','2021-09-27 16:00:59');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (82,'CXrT99RTnrg','저는 모든 여행을 응원합니다..만','https://i.ytimg.com/vi/CXrT99RTnrg/default.jpg','2023-02-14 18:27:43');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (83,'aDYX01gQqrE','제주도 해녀체험 🦀힘드네 ⚠사서고생 주의⚠ ㅣ뿔소라 진짜 잡힌다고? ㅣJEJU VLOG ㅣ제주브이로그ㅣ파친맴은 잠수중🥽','https://i.ytimg.com/vi/aDYX01gQqrE/default.jpg','2022-09-02 20:00:08');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (84,'Sr5gwLfN7fA','초보도 가능하다고??? ☞ 제주도 구좌읍 하도리 해녀 체험','https://i.ytimg.com/vi/Sr5gwLfN7fA/default.jpg','2021-08-02 19:07:39');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (85,'HAIIiOW7yQw','2박3일 해녀마을체험! 해녀마을스테이 in 김녕','https://i.ytimg.com/vi/HAIIiOW7yQw/default.jpg','2024-07-04 17:58:14');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (86,'7S7Ns-VrU0o','제주도 해녀체험 아빠 똥냄새?','https://i.ytimg.com/vi/7S7Ns-VrU0o/default.jpg','2024-11-12 09:01:59');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (87,'eFuP6aQrX6s','#2020빅맥송 제주해녀체험','https://i.ytimg.com/vi/eFuP6aQrX6s/default.jpg','2020-08-25 21:03:21');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (88,'sHuWMbtzBdY','제주해녀(濟州海女)','https://i.ytimg.com/vi/sHuWMbtzBdY/default.jpg','2015-09-10 08:43:59');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (89,'CjW3YWDQV6s','제주도 해녀체험 소개 #제주도여행 #제주도여행추천 #해물라면','https://i.ytimg.com/vi/CjW3YWDQV6s/default.jpg','2024-10-22 13:45:00');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (90,'3O_LNTFSe70','해양생물들과 함께하는 직업체험, 제주 해녀체험','https://i.ytimg.com/vi/3O_LNTFSe70/default.jpg','2022-01-31 04:24:03');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (91,'mLzTcItTfKk','제주 여행 브이로그| 애월, 애월 맛집, 해녀체험 도시해녀, 곽지해수욕장, 제주 LP바 마틸다, 서핑 문서프','https://i.ytimg.com/vi/mLzTcItTfKk/default.jpg','2023-08-20 12:28:32');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (92,'OKjDwiEypfs','제주도 해녀체험 |  [대신맨] 직업 체험을 대신해드림😆','https://i.ytimg.com/vi/OKjDwiEypfs/default.jpg','2020-06-18 13:30:03');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (93,'hXDSXAc3Epw','제주 스노쿨링 포인트 🤿 해녀 체험도 할 수 있는 법환포구','https://i.ytimg.com/vi/hXDSXAc3Epw/default.jpg','2024-08-17 11:33:01');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (94,'-mEJuPAicU4','도시해녀 문어잡기(제주도 해녀체험)','https://i.ytimg.com/vi/-mEJuPAicU4/default.jpg','2019-05-02 14:39:36');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (95,'9vcWgxLb2Ds','해녀가 전복을 캐는 장면을 똭! 포착! 제주해녀 육지에서 바다 속까지 밀착 촬영','https://i.ytimg.com/vi/9vcWgxLb2Ds/default.jpg','2020-04-02 20:43:15');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (96,'FUZJPmuprzc','제주도해녀체험','https://i.ytimg.com/vi/FUZJPmuprzc/default.jpg','2023-07-04 11:56:03');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (97,'PZTcPgjrYe4','Jeju 제주도 3- Haenyeo Experience; women divers in Jeju 제주해녀체험 [서귀포 Seogwipo] (with drone 4k)','https://i.ytimg.com/vi/PZTcPgjrYe4/default.jpg','2021-10-06 10:16:41');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (98,'NXWw4CRPQTc','제주도 해녀체험','https://i.ytimg.com/vi/NXWw4CRPQTc/default.jpg','2024-10-24 09:54:30');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (99,'5NdjkaDCFjU','제주 바다에서 흔하게(?) 일어나는 일 들','https://i.ytimg.com/vi/5NdjkaDCFjU/default.jpg','2020-08-26 16:02:33');
INSERT INTO youtube (`youtube_id`,`video_id`,`title`,`thumbnail_url`,`publish_time`) VALUES (100,'3afPr75rYuY','최악의 물가와 다 떠난다는 제주살이의 반전 현실을 보여드릴게요','https://i.ytimg.com/vi/3afPr75rYuY/default.jpg','2024-08-18 17:57:23');
